### ISSUE TITLE
Switch Command & Option Key

### ISSUE THREAD

**Issue by sazz** [rbreaves/kinto#655] opened 2022-04-30 17:08 UTC
Sorry for the noob question. I'm running Kubuntu 22.04 using an Apple Magic Keyboard. In MacOS I could configure the keyboard to swap both command and option keys.

Is there an easy way to do this with kinto.sh as well? 

As Keyboard I have selected in the system settings "Apple | Apple". In the advanced tab there are a lot of possible tweaks but I couldn't figure out the option to swap command & option.

Is this possible at all?

**Comment by rbreaves** [comment] 2022-05-01 05:31
Not what Kinto is designed for - that’d simple give you a Windows like layout. It’s meant to mimic Mac like hotkeys by mostly making Cmd(Super) = Ctrl, Alt = Alt & Ctrl = Super/Win.

Closing as this makes no sense for Kinto unless I misunderstand the question.

**Closed by rbreaves** 2022-05-01 05:31 UTC
Labels: question

**Comment by RedBearAK** [comment] 2022-05-01 07:24
>I'm running Kubuntu 22.04 using an Apple Magic Keyboard. In MacOS I could configure the keyboard to swap both command and option keys.

@sazz 

Your question is pretty confusing. Putting these two sentences together makes it sound like you swap the Cmd and Option keys on an actual Apple keyboard while using macOS. But that would make no sense. 

You would have to clarify what you're actually trying to do. Normally Kinto will simply make a Windows or Apple keyboard work exactly the same way as a standard Apple keyboard does on a Mac. There shouldn't be any problem with this on Kubuntu 22.04. Nothing should need to be swapped, if the correct keyboard type is selected. 

>As Keyboard I have selected in the system settings "Apple | Apple".

What exactly do you mean by selecting "Apple | Apple" in "system settings"? In Kinto's settings, or in Kubuntu's keyboard settings? In Kinto's context menu there is a list under "Keyboard Types" that looks like this: 

```
Windows
Apple
Chromebook
IBM (No Super/Win key)
Windows & Apple*
```

There is nothing in that list that says "Apple | Apple". This sounds like maybe you tried to change the keyboard type in the Kubuntu (KDE Plasma) keyboard settings. That's... not going to work well with Kinto. That may be your problem. Set the keyboard type back to defaults if you can.

**Comment by RedBearAK** [comment] 2022-05-01 07:53
@sazz @rbreaves 

Yeah, so I just booted up into the Kubuntu 22.04 live environment just to check on the KDE Plasma keyboard settings control panel, and it does have a very long list of keyboard types, one of which is "Apple | Apple". I think this is what the user has selected in this case, which seems logical but probably screwed up the remapping of the modifier keys. 

So... Should the user set the keyboard to "Generic | Generic 104-key" and then set the keyboard type in Kinto to "Apple", or should the user leave the keyboard set to "Apple | Apple" in the KDE Plasma control panel and set Kinto so "Windows"? 

Setting the keyboard to "Apple | Apple" probably swaps the Cmd and Option keys, and then Kinto, if it is using "Apple" as the keyboard type just swaps them back, so the user isn't getting the expected behavior. Thus the request for a way to swap the Cmd and Option keys yet again. 

I've never actually tried to set an Apple keyboard to "Apple | Apple" in KDE Plasma settings, so this is all new to me. I'll have to boot up Kubuntu 22.04 on an actual Mac and see what it identifies the keyboard as, other than "Generic | Generic 104-key".

**Comment by RedBearAK** [comment] 2022-05-01 09:12
@sazz @rbreaves 

I installed Kubuntu 22.04 on a 2008 MacBook Pro just to see how it would see the Apple keyboard. The KDE Plasma "Input => Keyboard" control panel identified the keyboard by default as "Generic | Generic 104-key PC". 

@sazz, if you change your keyboard setting for the Apple Magic Keyboard back to this generic setting instead of "Apple | Apple", the keyboard shortcuts should work as expected with Kinto. As long as Kinto is set to use the "Apple" keyboard type, it should correctly remap the modifier keys. That can be changed from the Kinto GUI app or the Kinto icon in the tray (if you can see the Kinto tray icon).

**Comment by sazz** [comment] 2022-05-01 09:14
Sorry for the confusing question.

So in MacOS there is the dialog to swap control & option key:

![image](https://user-images.githubusercontent.com/4020377/166139642-a69d382f-3f3b-4d20-b327-a8d756578fe1.png)

(taken from https://apple.stackexchange.com/questions/280855/changing-right-hand-command-alt-key-order-to-be-like-a-windows-keyboard)

It's not about trying to mimic Windows layout but stay to the the mac shortcut system (which I think is superior to Windows) but with having the option & control key swapped.

But maybe my fault is in having the Kubuntu not configured correctly to meet kinto.sh expectations.

Is there any documentation what needs to be prepared in Kubuntu (configuration sides e.g. setting locale, keyboard, etc.) to make kinto happy?

**Comment by RedBearAK** [comment] 2022-05-01 09:19
@sazz 

>So in MacOS there is the dialog to swap control & option key:

Yes, I've had to use a PC keyboard with macOS many times, I know what you're talking about on that side. But when running Linux and Kinto the appropriate remapping of the modifier keys should happen automatically. That was what the dev designed Kinto to do. 

Read my other posts here about changing the keyboard setting in Kubuntu (which uses KDE Plasma as its desktop environment, as I'm sure you know) back to "Generic | Generic 104-key PC". Then Kinto should work as expected.

**Comment by sazz** [comment] 2022-05-01 09:24
Changing back the layout to Generic | Generic 104-key PC did the trick. Thank you a lot!

**Comment by RedBearAK** [comment] 2022-05-01 09:29
> Changing back the layout to Generic | Generic 104-key PC did the trick. Thank you a lot!

@sazz @rbreaves 

Thanks for confirming the mystery is solved. Have fun!
