### ISSUE TITLE
[QUESTION] Disabling "Q" or "Alt+Q" in the Alt+Tab switcher? 

### ISSUE THREAD

**Issue by RedBearAK** [rbreaves/kinto#419] opened 2021-03-11 22:24 UTC
Someone on the Cinnamon GitHub was expressing frustration with the fact that applications will quit immediately if you happen to press "Q" while using the Alt+Tab switcher (or more likely Alt+Q since it happens while the Alt+Tab switcher is active onscreen). 

I was thinking maybe a barebones xkeysnail config file could be a way to stopgap this problem, but then I got stumped by the fact that `xprop -spy` doesn't return anything useful when I click on the Alt+Tab switcher window. So I don't know how a remap could be applied only to the Alt+Tab switcher while still allowing Alt+Q to be used in Chrome the way they are using it. 

Any idea how to apply a key mapping just to the Alt+Tab switcher? I'm guessing maybe you never had to identify the actual WM_CLASS of the switcher because it's just a general defined system shortcut. But I thought I would ask. 

There is unfortunately no listed keyboard shortcut in Cinnamon that could be used to easily disable the "quit app" function of the app switcher. It seems to be a function built into the switcher itself, and the Cinnamon team would have to set it up as a toggle option in Windows preferences dialog.

**Comment by rbreaves** [comment] 2021-03-11 23:53
Well I noticed recently that someone made use of checking if WM_CLASS is equal to empty.. so ( WM_CLASS == ''  ) using that lambda thing in the kinto.py for synergy since it does not report either - but yes it creates the potential for a keymap to be applied when no class name is being reported at all and that would end up applying to multiple apps or use cases. May work still.

**Comment by RedBearAK** [comment] 2021-03-12 00:34
@rbreaves 

Thanks, I'll give that a try sometime and see what happens.

**Comment by RedBearAK** [comment] 2021-03-13 04:48
@rbreaves 

Very long story very short: The emtpy WM_CLASS trick does not seem to work on the Alt+Tab switcher. 

Through a different method I have it working in some sense, but when I try to start cleaning out the unnecessary bits (all the other Mac-oriented shortcut mappings), suddenly it stops working at some point. 

But before I strip out the wrong thing, I'm able to 
1) disable the modifier key remapping, so everything is "normal", then 
2) block Alt+Q in the main block so it's blocked in Alt+Tab, then 
3) remap Alt+Q to something like Alt+W, but only for Chrome(s). 

For some reason it doesn't work to just map Alt+Q to Alt+Q or use pass_through_key to make it continue working in Chrome/Chromium, that causes Chrome to not see the Alt key when pressing Alt+Q. So if the user ultimately ends up using this modified `kinto.py` file they will have to change the actual keyboard shortcut that activates their tabbing extension, which is pretty easy within Chrome. But they would be able to keep using physical Alt+Q like they wanted. And it will no longer [Q]uit applications while task switching. 

Just need to figure out what keeps breaking things when I start stripping out the other shortcuts that might cause unwanted side effects. But I think ultimately this can work. 

I'm open to suggestions for something more innocuous than Alt+W to map to, if you think that might conflict with something.

**Comment by RedBearAK** [comment] 2021-03-13 05:10
@rbreaves 

So this is all I have left, and it's still working. Well, if I hadn't kept a few instances of the GUI app window running the whole time, I would have to be using the tray icon to restart, because at some point the GUI will start bringing up a dialog asking if you have other remappers running. But with a GUI window still running I'm still able to restart Kinto and see the logs. 

```
# -*- coding: utf-8 -*-
# autostart = true

import re
from xkeysnail.transform import *

# Use the following for testing terminal keymaps
# terminals = [ "", ... ]
# xbindkeys -mk
terminals = ["kinto-gui.py","gnome-terminal","konsole","io.elementary.terminal","terminator","sakura","guake","tilda","xterm","eterm","kitty","alacritty","mate-terminal","tilix","xfce4-terminal","hyper"]
terminals = [term.casefold() for term in terminals]
termStr = "|".join(str(x) for x in terminals)

mscodes = ["code","vscodium"]
codeStr = "|".join(str(x) for x in mscodes)

# Add remote desktop clients & VM software here
# Ideally we'd only exclude the client window,
# but that may not be easily done.
remotes = ["org.remmina.Remmina","xfreerdp"]
remotes = [client.casefold() for client in remotes]

# Add remote desktop clients & VMs for no remapping
terminals.extend(remotes)
mscodes.extend(remotes)

# Use for browser specific hotkeys
browsers = ["Chromium","Chromium-browser","Google-chrome","microsoft-edge-dev","microsoft-edge","Epiphany","Firefox","Discord"]
browsers = [browser.casefold() for browser in browsers]
browserStr = "|".join(str(x) for x in browsers)

chromes = ["Chromium","Chromium-browser","Google-chrome","microsoft-edge-dev","microsoft-edge"]
chromes = [chrome.casefold() for chrome in chromes]
chromeStr = "|".join(str(x) for x in chromes)

# edges = ["microsoft-edge-dev","microsoft-edge"]
# edges = [edge.casefold() for edge in edges]
# edgeStr = "|".join(str(x) for x in edges)

define_multipurpose_modmap(
    # {Key.ENTER: [Key.ENTER, Key.RIGHT_CTRL]   # Enter2Cmd
    # {Key.CAPSLOCK: [Key.ESC, Key.RIGHT_CTRL]  # Caps2Esc
    # {Key.LEFT_META: [Key.ESC, Key.RIGHT_CTRL] # Caps2Esc - Chromebook
    {                                         # Placeholder
})

define_keymap(re.compile(chromeStr, re.IGNORECASE),{
    K("M-q"): K("M-w"),     # Map Alt+Q to Alt+W, but only within Chrome/Chromium
})

# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("M-q"): K("Esc"),         # disable quitting applications in Alt+Tab app switcher
})

define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("M-q"): K("Esc"),         # disable quitting applications in Alt+Tab app switcher
}, "terminals")
```

**Comment by rbreaves** [comment] 2021-03-13 05:24
To be honest this is a fairly extreme edge case I feel like and is highly dependent on the DE and its app switcher. Given what I know already about finicky app switchers in DEs and patching one of them (Budgie) - I really don't have much interest in trying to suss this sort of issue out for each one.

Even if I were to do so - the behavior it should do, to line up with macOS, is to actually close the currently highlighted app in the app switcher, Budgie does not currently do this. Budgie will only close the current app that had focus before the app switcher appeared. It's also difficult to even imagine a workable solution for App Switchers in general - if they don't have the expected behavior because you typically have to keep control held for the app switcher to remain open. If you have to deviate from that to close an app or if it triggers the closing of the app switcher then that just really sucks.

All in all the behavior you describe happening in Cinnamon where apps close on Q after hitting Alt-Tab lines up perfectly with macOS. Frustration for some users or not this would be an addition for a tweaks menu item at most and not to ever go in as a default. You're welcomed to continue working on it and submit a PR if you want, even one with commented out code someone can uncomment back in manually, but I will be closing this thread.

**Closed by rbreaves** 2021-03-13 05:24 UTC
Labels: question

**Comment by RedBearAK** [comment] 2021-03-13 06:38
@rbreaves 

Yeah, that's fine. This was really just an exercise I was doing because it seemed for sure that xkeysnail (and the Kinto tray tool) had the ability to easily solve this problem for those who are running afoul of it. 

I gave them a set of instructions to follow to install Kinto and copy my basic file into place. It will be a miracle if they follow through, and a double miracle if it actually solves their problem. 

https://github.com/linuxmint/cinnamon/issues/9787#issuecomment-797875281

> Even if I were to do so - the behavior it should do, to line up with macOS, is to actually close the currently highlighted app in the app switcher, Budgie does not currently do this. Budgie will only close the current app that had focus before the app switcher appeared. It's also difficult to even imagine a workable solution for App Switchers in general - if they don't have the expected behavior because you typically have to keep control held for the app switcher to remain open. If you have to deviate from that to close an app or if it triggers the closing of the app switcher then that just really sucks.

Yeah, the real solution needs to be implemented by the DE maintainers. Just a simple toggle switch. 

I know macOS has always done this but I didn't know for a very long time, yet strangely I never had a problem with doing it by accident even though I was Cmd+Tabbing and Cmd+Q'ing all day long for decades. But this guy, he's apparently trained himself to use a Chrome tab-switching extension that uses Alt+Q by default (there are several that do this). Plus an ergonomic keyboard that makes it easy to miss the Tab key. So I just wanted to help if possible. 

I don't even know how I would submit a PR, since the "solution" I came up with that works just disables Alt+Q everywhere, and then the user would have to re-enable it per application. It's a real sledgehammer. 

Although, is there really any other application besides these Chrome extensions that are silly enough to try and use Alt+Q? Maybe it would be good enough to just do what I just did, and add it in as a tweak option. Anybody else would need to fix Alt+Q in their app manually. 

> Also the pass_through_key is not what it sounds like - it actually intentionally cancels out that particular key so that it literally does not pass_through - it blocks it from going through. I cancel out the newly mapped location of the alt key while remapping the Cmd key location to be Alt-Tab at the same time. This also only works because of my custom fork of xkeysnail. Otherwise the tab switcher would typically appear and quickly disappear because held keys is not a real concept in xkeysnail by default.

Aha, very interesting.

**Comment by RedBearAK** [comment] 2021-03-13 11:13
@rbreaves 

So, the person I was trying to help turned out to be a lot more knowledgeable than me. They took my description, understood the problem, and then just made their own simple config file for xkeysnail. And it worked! It solved their problem with Alt+Q. So that's nice. Thanks for helping me figure so many things out. 

Here's what he put together, probably in a matter of minutes. Much simpler than mine. Of course, silly me, I didn't realize you could just map a key combo to "None". That's kind of what I was looking for, just didn't know the right syntax to invoke it. Very nice solution. 

```
import re
from xkeysnail.transform import *

# Map Alt+Q to Alt+W, but only within Chrome/Chromium
chromeStr = "|".join(str(x.casefold()) for x in ["Chromium","Chromium-browser","Google-chrome","microsoft-edge-dev","microsoft-edge"])
define_keymap(re.compile(chromeStr, re.IGNORECASE), {
    K("M-q"): K("M-w"),
})

# Everywhere else, including the Alt+Tab switcher, ignore Alt+Q entirely.
define_keymap(None, {
    K("M-q"): None,
})
```
