### ISSUE TITLE
Win + shift + arrow (left or right) should highlight a word but opens the menu bar in an application

### ISSUE THREAD

**Issue by GijsGoudzwaard** [rbreaves/kinto#630] opened 2022-02-24 09:50 UTC
**Describe the bug**
Win + shift + arrow (left or right) should highlight a word but opens the menu bar in an application (menu bar is the bar with "File, Edit, View, Window, Help etc). This goes wrong in apps like slack or notion (electron based applications). With this bug I can't properly select text through my keyboard and.

**Expected behavior**
It should highlight the word without opening the menu bar in the application.

**Install Type:** Bare Metal
**Distro:** Ubuntu 20.04.4 LTS
**DE:** Gnome
**Branch:** master
**Commit:** latest

**Comment by rbreaves** [comment] 2022-02-24 19:51
Pretty sure this probably comes from a custom remap you had done. There is no reason at all why the app launcher menu would open up with the key combo. I use this daily and on Ubuntu Budgie - the keymaps are pretty identical to Ubuntu and I know that combo would not open the app launcher in any way.

Only explanation is that it is cause by a custom remap you had already done imo. Closing. If you disagree then please dump your system level remaps on gnome and post them here.

**Closed by rbreaves** 2022-02-24 19:51 UTC
Labels: bug

**Comment by GijsGoudzwaard** [comment] 2022-02-24 20:01
I haven't done any custom configs besides installing kinto sh and setting it to the windows & apple profile. 

How can I get my system level remaps using dconf? Not sure where to find them

**Comment by rbreaves** [comment] 2022-02-24 20:39
Well you may just want to uninstall Kinto and reinstall it because it perhaps something didn't get set right.

to dump keys
`dconf dump /org/gnome/desktop/wm/keybindings/ > tempkb.conf`

To see what your app launcher hotkey is set to (on the gnome level any ways)
`gsettings get org.gnome.mutter overlay-key`

To remove keymaps to app launcher
`gsettings set org.gnome.mutter overlay-key ''`

To re-add app launcher
`gsettings set org.gnome.mutter overlay-key 'super'`

At any rate I am pretty certain the issue is not with Kinto. There's just not much way for it do what you are describing unless some other configuration occurred. I (& others) have tested this app well enough to know that that key combo can't or shouldn't happen on a stock Ubuntu install. I am not trying to be rude, but I am pretty certain another application or configuration is interfering that is unrelated to Kinto.

Although uninstalling Kinto, deleting it and redownloading could help even as there was 1 bug that existed weeks ago actually due to a dependency issue with xkeysnail that has since been resolved. That could have caused some hotkey combo issues actually. Will re-open if you can confirm that it is not caused by another application or configuration outside of Kinto or duplicate this issue on a new install or VM of Ubuntu.

**Comment by GijsGoudzwaard** [comment] 2022-02-25 07:34
Would it at all be possible to not do anything when the `alt` key is pressed? It seems that windows users fix this issue with autohotkey, though i do not know if the same is possible with kinto. https://superuser.com/a/615424

**Comment by rbreaves** [comment] 2022-02-25 14:04
I’ve done a lot of testing on this in vscode & while you can setup the key maps which will then help to ignore the alt menu activations - you can’t simply remap that combo in Kinto alone.

I have a complicated vscode remap that does work perfectly but have not yet scripted. And how to apply it to Electron apps that don’t offer remapping is unknown to me at this time. There ought to be similar tickets on this already, closed or open there’s no ETA on a fix.

I’m interested in a fix as yes Electron apps on Windows has less of an issue w/ this, but until someone finds a fix for Linux Electron apps the alt menu will continue to cause interference.
