### ISSUE TITLE
Ubuntu 18.04 arrow key not working while changing the application

### ISSUE THREAD

**Issue by yugyesh** [rbreaves/kinto#545] opened 2021-07-07 09:47 UTC
**Describe the bug**
The arrow key doesn't work when changing the application (The application change window appears after clicking cmd + tab)

**Expected behavior**
![Screenshot from 2021-07-07 18-48-00](https://user-images.githubusercontent.com/17958722/124738424-df813a80-df53-11eb-84bb-6cd1e34f9bb4.png)

**Comment by rbreaves** [comment] 2021-07-08 04:43
Closing. Duplicate of #409

**Closed by rbreaves** 2021-07-08 04:43 UTC
Labels: bug
