### ISSUE TITLE
Alt+[Key] Shortcuts don't work in terminal

### ISSUE THREAD

**Issue by NonVideri** [rbreaves/kinto#641] opened 2022-03-27 16:10 UTC
**Describe the bug**
The Alt (M) modifier doesn't seem to do anything when put into the last ("terminals") keybindings.

**Expected behavior**
    K("M-Backspace"): K("M-Shift-Backspace"),
    K("M-Delete"): K("M-Shift-Delete"),
should remap the Alt+Backspace and Alt+Delete to their shifted versions.

**Actual behavior**
It doesn't work. (Neither does it work with remapping these combinations to other mappings.)
Everything else works perfectly fine.

**Install Type:** Bare Metal
**Distro:** Manjaro (5.15.28-1-MANJARO)
**DE:** KDE
**Branch:** master
**Commit:** newest version

**Comment by rbreaves** [comment] 2022-03-28 23:51
Use `xprop -spy` & confirm the terminal app name (wm_class) exists in kinto.py config file. It should work.

**Comment by RedBearAK** [comment] 2022-04-19 00:32
@rbreaves @NonVideri 

Ben, I don't think this has to do with the terminal app not being in the WM_CLASS list. I think this is another "wordwise" conflict with identical shortcut remaps in the GUI block. I can confirm that GNOME Terminal on my Ubunto 21.10 install does not respond correctly to at least the M+Backspace shortcut without an override placed above the GUI block. 

I'm assuming here that Option+Backspace on a Mac is supposed to "delete word left of cursor", and Option+Delete should "delete word right of cursor". These are NOT enabled by default on macOS, as far as I can tell, but a lot of people do enable them. 

Apparently in terminals there is a difference between a "WORD" which is any set of contiguous characters other than whitespace, and a "word" which is just what we would normally consider a word in general editing, characters separated by whitespace or punctuation. When enabled, Option+Backspace and Option+Delete appear to do the normal "word" deletion. So Ctrl+W would delete "asdf/asdf/asdf" all at once, but Opt+Backspace would turn "asdf/asdf/asdf" into "asdf/asdf/". 

It's necessary to enable "Use Option as Meta key" in the Profile: Keyboard settings in Apple's Terminal app to make this work. This has to be enabled for each profile individually. Option+Backspace will then start deleting words. But the user needs to add the Option+Delete shortcut to the shortcuts list manually to get that to work, as Action: Send Text: \033d (entered by pressing Escape, then "d"). (Testing on a MacBook Pro with Mojave.)

So, that's how that works on the Mac side (I'm learning as I go). Now let's look at why it doesn't work as the user expected on Linux with Kinto. 

On the Linux side, there is already an M-Backspace and M-Delete (actually it's "Alt-Delete" in the config file, that should probably be fixed). But these shortcuts are part of the "wordwise" shortcuts in the "General GUI" section. Because this section is above the "termStr" block in the config file, it will override any identical remap placed inside the "termStr" block. I have run into this problem with the shortcuts needed to enable terminal tab navigation with arrow keys. The only solution to overcome this conflict was to place a small secondary "termStr" block just above the "General GUI" block, like this: 

```
# Special overrides for terminals for shortcuts that conflict with General GUI block below.
define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("RC-Shift-Left"):         K("C-Page_Up"),                                 # Go to prior tab (Left)
    K("RC-Shift-Right"):        K("C-Page_Down"),                               # Go to next tab (Right)
},"Special overrides for terminals")

# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-Shift-Left_Brace"):       K("C-Page_Up"),                             # Go to prior (left) tab
    K("RC-Shift-Right_Brace"):      K("C-Page_Down"),                           # Go to next (right) tab
    K("F9"):                K("Mute"),                                          # Turn F9 into mute button
...
```

I'm still in the process of investigating this as I write, but I'm pretty sure these shortcuts will need to be added to this special override block to get them to work. 

OK, looks like for me the M+Delete in the "General GUI" block that remaps to Ctrl+Delete seems to work fine. But the terminal wants M+Backspace to remap to M+Shift+Backspace instead of Ctrl+Shift+Backspace, which just does a normal character deletion. 

So this would be a minimal fix just to get Opt+Backspace working, as far as I can tell (just the first block, placed right above the "General GUI" block): 

```
# Special overrides for terminals for shortcuts that conflict with General GUI block below.
define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("M-Backspace"): K("M-Shift-Backspace"),               # Wordwise - delete word left of cursor in terminals
},"Special overrides for terminals")

# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-Shift-Left_Brace"):       K("C-Page_Up"),                             # Go to prior (left) tab
    K("RC-Shift-Right_Brace"):      K("C-Page_Down"),                           # Go to next (right) tab
    K("F9"):                K("Mute"),                                          # Turn F9 into mute button
...
```

The following would also work, with an alternate shortcut of "Escape, then d" being sent to terminals for Opt+Delete, and this also enables the alternate terminal tab navigation shortcuts of Cmd+Shift+Left/Right (Cmd+Shift+Braces should already work for that): 

```
# Special overrides for terminals for shortcuts that conflict with General GUI block below.
define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("M-Backspace"): K("M-Shift-Backspace"),               # Wordwise - delete word left of cursor in terminals
    K("M-Delete"): [K("Esc"),K("d")],                       # Wordwise - delete word right of cursor in terminals
    K("RC-Shift-Left"):         K("C-Page_Up"),                                 # Go to prior tab (Left)
    K("RC-Shift-Right"):        K("C-Page_Down"),                               # Go to next tab (Right)
},"Special overrides for terminals")

# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-Shift-Left_Brace"):       K("C-Page_Up"),                             # Go to prior (left) tab
    K("RC-Shift-Right_Brace"):      K("C-Page_Down"),                           # Go to next (right) tab
    K("F9"):                K("Mute"),                                          # Turn F9 into mute button
...
```

The shortcuts to delete line to left or right of the cursor don't seem to work in Apple's Terminal app the way they do in GUI apps, at least not without manual intervention. But if you also want to activate those in Linux terminals (Cmd+Backspace and Cmd+Delete), these two additional lines should do the job (maps to Ctrl+U and Ctrl+K): 

```
# Special overrides for terminals for shortcuts that conflict with General GUI block below.
define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("M-Backspace"):       K("M-Shift-Backspace"),             # Wordwise - delete word left of cursor in terminals
    K("M-Delete"):          [K("Esc"),K("d")],                  # Wordwise - delete word right of cursor in terminals
    K("RC-Backspace"):      K("C-u"),                           # Wordwise - delete line left of cursor in terminals
    K("RC-Delete"):         K("C-k"),                           # Wordwise - delete line right of cursor in terminals
    K("RC-Shift-Left"):     K("C-Page_Up"),                     # Go to prior tab (Left)
    K("RC-Shift-Right"):    K("C-Page_Down"),                   # Go to next tab (Right)
},"Special overrides for terminals")

# None referenced here originally
# - but remote clients and VM software ought to be set here
# These are the typical remaps for ALL GUI based apps
define_keymap(lambda wm_class: wm_class.casefold() not in remotes,{
    K("RC-Shift-Left_Brace"):       K("C-Page_Up"),                             # Go to prior (left) tab
    K("RC-Shift-Right_Brace"):      K("C-Page_Down"),                           # Go to next (right) tab
    K("F9"):                K("Mute"),                                          # Turn F9 into mute button
...
```

Pretty sure these are remapping to standard shortcuts that all Linux terminals should understand, so even though I'm testing in GNOME Terminal this should apply just as well to Konsole in KDE, or anything else. But I could be wrong.

**Comment by NonVideri** [comment] 2022-04-24 10:53
I followed your advice and placed this block above the General GUI.
```py
# Special overrides for terminals for shortcuts that conflict with General GUI block below.
# Place M-X or Alt-X shortcuts for terminal here.
define_keymap(re.compile(termStr, re.IGNORECASE),{
    K("M-Backspace"): K("M-Shift-Backspace"), # Deleting lines in ZSH
    K("M-Delete"): K("M-Shift-Delete"),      
},"Special overrides for terminals")
```
This finally worked and allowed me to set up proper shorcuts in .zshrc file. Thank you!

**Comment by RedBearAK** [comment] 2022-04-25 01:18
> This finally worked and allowed me to set up proper shorcuts in .zshrc file. 
> Thank you!

Glad that I was able to be a bit helpful. Looks good.

**Comment by RedBearAK** [comment] 2022-05-20 09:12
@rbreaves @NonVideri 

PR #671 should close this issue, if accepted.

**Closed** 2022-05-21 05:18 UTC
Labels: bug
