### ISSUE TITLE
Kinto.ahk resets after upgrade or switching keyboard type

### ISSUE THREAD

**Issue by pyrocat101** [rbreaves/kinto#493] opened 2021-05-02 21:23 UTC
**Describe the bug**

On Windows, modifications to kinto.ahk got overwritten whenever I switch keyboard type or upgrade. My custom keyboard remaps are lost.

**Expected behavior**

kinto.ahk should preserve my modifications.

**Install Type:** Bare Metal
**Distro:** Windows 10
**DE:** N/A
**Branch:** master
**Commit:** dbd6147

**Comment by rbreaves** [comment] 2021-05-02 21:56
Hmmm.. well I definitely need to fix that. I have seen it get in a bad state before but I am not entirely sure of how or why that occurred previously. I don't think I've been able to replicate that any for awhile though and may have only impacted a specific version immediately after install some versions ago and was followed up with a patch.

Can you tell me how I might replicate this problem, specifically which keyboard types triggers this event after the install and which ones seem unaffected? I mean I should be able to replicate it either way if the bug was re-introduced somehow but it would get me to the right section of the code a bit faster.

**Comment by pyrocat101** [comment] 2021-05-02 22:09
@rbreaves Thanks for the quick response!

The minimum repro for me so far is to:

1. On a Windows machine, edit kinto.ahk to uncomment this line:

```
; SetCapsLockState, AlwaysOff ; CB/IBM
```

2. Now you can either reinstall Kinto via `setup.py`, or just use the tray icon to switch to a different keyboard.
3. Check `kinto.ahk` again and the file is overwritten back to the "factory state".

**Comment by rbreaves** [comment] 2021-05-02 22:46
Oh.. well yea - currently installing Kinto from the setup will overwrite any modifications you may, I have no ability to parse out your changes and keep them during upgrades. I should implement a backup though in a future update so that you can easily restore your changes manually.

I have been putting some thought into changing the config file for linux/xkeysnail and those changes could also be applied to autohotkey as well. The direction I plan to go in is to convert the current the configs kinto.ahk and kinto.py unto yaml and be able to convert that back into the ahk or py config files.

By switching to yaml configs in the near future you'd be able to easily keep your changes during upgrades without losing them or manually backing up your config before upgrading.

**Comment by rbreaves** [comment] 2021-05-02 22:50
This discussion is really a duplicate of this PR https://github.com/rbreaves/kinto/pull/455, so I am closing this issue ticket.

**Closed by rbreaves** 2021-05-02 22:50 UTC
Labels: bug

**Comment by pyrocat101** [comment] 2021-05-03 03:29
> I am not sure what you mean by saying switching keyboard types resets to factory though, there's really no functionality in Kinto that would override your modifications unless you initiate a new setup.py install. 

Are you able to reproduce this on your end?

**Comment by rbreaves** [comment] 2021-05-03 03:36
Well there's simply not a fix to prevent it from overwriting your modifications on re-running the setup.py or doing an upgrade until I update/rewrite the installer.

When it comes to switching keyboard types, I can already confirm that changing keyboard types on my local system does not change behavior, but I will do another run through via a VM to make sure given that you report otherwise on that point.

**Comment by rbreaves** [comment] 2021-05-03 04:13
As expected, adding a fake region screenshot remap stays in place like I'd expect, while the modifier keys shift around as I'd expect them to. This is why I already closed the ticket - I know there is no functionality in the script that would remove your custom remaps from simply changing your keyboard type via the system tray app - BUT if you reinstall it then yes, you will lose your custom remaps that you may add to the script.

I will try and address that latter issue in a future update, but this ticket will remain closed (duplicate) and I am not able to reproduce your other issue when I change from Windows to Mac and back again. The modifiers shift as they should, but the custom remaps remain. If you have more information or a video you can provide it would give me something more to work with, or the code of your specific custom remap.

```
...
   ; Region Screenshot
    ^+4::Send #+{S}

    ; Fake Region Screenshot - Added this
    ^+5::Send #+{S}
...
```

**Comment by pyrocat101** [comment] 2021-05-03 04:34
@rbreaves have you tried my example above that uncomments this line?

```
; SetCapsLockState, AlwaysOff ; CB/IBM
```

**Comment by rbreaves** [comment] 2021-05-03 05:14
@pyrocat101 Looks like that line of code works fine for me, it doesn't disappear when switching keyboard types. It activates under chromebook or IBM kb types.

One thing you could try is this, close the app via the system tray, modify the kinto.ahk file in the %userprofile%\.kinto\kinto.py location. Then browse to "%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup" and run the kinto-start.vbs file or run it from %userprofile%\.kinto\kinto-start.vbs.
