### ISSUE TITLE
Crashes on Ubuntu 18.04 after login, black screen

### ISSUE THREAD

**Issue by sebastian-ruiz** [rbreaves/kinto#126] opened 2020-04-27 17:15 UTC
**Describe the bug**
After login I have a couple of seconds on my desktop before the screen goes black. I can't do anything anymore. I can hold the power button to turn off the machine. 

**Expected behavior**
I expected to be able to use Ubuntu as normal but now with Mac shortcuts

**Install Type:** Bare Metal, running on Dell XPS 13 9360 alongside windows
**Distro:** Ubuntu 18.04 LTS
**DE:** Gnome
**Branch:** release 1.0.7-2, zip file (latest at time of writing)

**Kinto Input Caret Status**
```
cat /tmp/kinto/caret
```

**Kinto Standard Log**
```
journalctl --user-unit=keyswap.service -b
```
**Kinto Debug Log (1.0.6-2+)**
```
systemctl --user stop keyswap
cd ~/.config/kinto
./kintox11 --debug
```

**Comment by rbreaves** [comment] 2020-04-27 17:31
Just tested it on my 18.04 VM, but no issue. I will look at setting up another Ubuntu 18.04 VM though as I don't care for how I configured this VM any ways.

Please provide me with more debug info/logs so I can better determine your issue. Even if I can't replicate your issue perfectly it is sometimes possible for me to create a similar error in my logs so that I can at least sorta address the issue, even if not directly. You can also DM me on twitter, gbit86 and I'd be open to doing a remote session even. You're not the only person having reported this type of issue and it is concerning to me.

Having said that though, you can also try the xkeysnail implementation under the dev branch while will be merged into master in the coming days. It may prove to be much more stable/reliable for you than the xkb implementation.

**Comment by sebastian-ruiz** [comment] 2020-04-27 20:56
I couldn't manage to get the logs, because whenever I tried to login my screen would go black immediately. The only way I fixed it was to reinstall ubuntu (it was an almost fresh install anyway). I found that version 1.0.6-4 doesn't have the same issue and works fine.

**Comment by rbreaves** [comment] 2020-04-27 21:01
hmmm well I am disturbed that systemd doesn't recognize the failure and shut off the service as a result. I would think in most cases of a service failure that would be the result when you reboot your system.

**Comment by rbreaves** [comment] 2020-04-27 21:19
There is a pretty big leap in features and functionality between 1.0.6-4 and 1.0.7. I implemented new keymaps (specically changes in the types files) and added multithreading to handle better caret checking. I'd think it be more likely the the types files are crashing xkb. It shouldn't be, but it seems like I have been bumping up against some sort of bug in xkb. It can probably be worked around and resolved, but I have to duplicate it first. I may try working with a native install of ubuntu on something in the coming days, maybe I just can't create the issue in a VM.

.xkb/types/mac_gui
 .xkb/types/mac_term

https://github.com/rbreaves/kinto/compare/1.0.6-4...1.0.7

**Comment by rbreaves** [comment] 2020-04-27 22:11
When that crashed occurred did it look like this? @sebastian-ruiz 
<img width="798" alt="Screen Shot 2020-04-27 at 5 11 00 PM" src="https://user-images.githubusercontent.com/10969616/80425876-2c767500-88aa-11ea-8965-70714debe515.png">

**Comment by rbreaves** [comment] 2020-04-27 22:16
I believe this to be a duplicate of https://github.com/rbreaves/kinto/issues/112, so I am actually going to close this thread. If you have any further information you can post in the other thread going forward.

**Closed by rbreaves** 2020-04-27 22:16 UTC
Labels: bug
