### ISSUE TITLE
Cmd+Q and Cmd+H not working

### ISSUE THREAD

**Issue by burakerdem** [rbreaves/kinto#281] opened 2020-09-29 22:05 UTC
I installed Kinto on Ubuntu 20.04.1 on a MacBook Air mid-2011. It just worked fine after installation but Cmd+Q and Cmd+H stopped working after restarting the computer. Instead of Cmd+H, Ctrl+H is working and Cmd+Q does nothing.

**Install Type:** Bare Metal
**Distro:** Ubuntu 20.04.1
**DE:** Gnome 3.36.3
**Branch:** master
**Commit:** 139cff1

**Comment by rbreaves** [comment] 2020-09-30 18:42
My advice on fixing it quickly & in a way that’ll persist across reboots is to open up your keyboard settings & reset those specific shortcuts to your expected key combos.

Also I think I need to add some logic/script for cmd+h or whatever combo it is supposed to be to hide all windows & to hide all but the current window as well. I added that to the Windows part but haven’t added it to Linux yet.

\/ What’s likely going on \/

Sounds like some OS level remapping did not stick. This was a bug in earlier builds that I thought had been fully resolved as the solution was to dump the entire OS level shortcut key remaps (After I already modified them) that get added via dconf I believe & then re-import them all.

I found by doing that shortcut keys added via dconf would then be properly retained across reboots. If that behavior is no longer the case then I need to investigate this further.

**Comment by burakerdem** [comment] 2020-09-30 20:11
I'm posting here three screenshots.

First one is the default keyboard shortcut for "hide window" which tells me that it's "Super+H" (which doesn't work).

![Screenshot from 2020-09-30 23-00-37](https://user-images.githubusercontent.com/244163/94733999-3b89b380-0371-11eb-8915-141e51fc7ac1.png)

When I change this shortcut by pressing "Cmd+H" it shows "F9" instead of "Super+H". If I save this shortcut, it becomes "F9" and interestingly "F9" really works. But I've never pressed "F9".

![Screenshot from 2020-09-30 23-01-09](https://user-images.githubusercontent.com/244163/94734202-93281f00-0371-11eb-8279-f8d2926e38a0.png)
![Screenshot from 2020-09-30 23-01-16](https://user-images.githubusercontent.com/244163/94734208-94594c00-0371-11eb-9f17-f98b409b8a48.png)

It's the same for "close window". It's "Alt+F4" by default and if I change it to "Cmd+Q" it displays "F4" instead of "Cmd+Q".

![Screenshot from 2020-09-30 23-10-31](https://user-images.githubusercontent.com/244163/94734628-29f4db80-0372-11eb-9116-9abf386031f3.png)

![Screenshot from 2020-09-30 23-09-12](https://user-images.githubusercontent.com/244163/94734561-16e20b80-0372-11eb-9ab1-07b064623e27.png)

I'm not sure how I can reset those specific shortcuts.

**Comment by rbreaves** [comment] 2020-10-01 06:41
That is really bizarre, and would be the source of your difficulties. It appears like it is not passing through your Alt key and I have never seen that occur so I am not really sure what the cause of that would be.. but when you hold down "Cmd+Q" it should be Alt+F4 and likewise I suppose Cmd+H should be Alt+F9.

I do plan to rewrite part of the program after the system tray release that will make fewer, maybe no permanent or persistent shortcut key changes on the distro level. Although.. if your Cmd key position is not being transformed in the Alt + (?) shortcut keys then I that sounds like the issue may not go away for you still. I am not sure what to suggest next if your Cmd key is not switching over to Alt the moment you hit Q or H..

**Comment by burakerdem** [comment] 2020-10-01 15:43
I think I've found the problem. After installing Ubuntu, I've changed ALT key mapping.

    Gnome Tweaks > Keyboard & Mouse > Additional Layout Options > Key to choose the 3rd level > Any Alt

![Screenshot from 2020-10-01 18-42-30](https://user-images.githubusercontent.com/244163/94831869-e358bd00-0415-11eb-8bce-379706c0d362.png)

![Screenshot from 2020-10-01 18-29-31](https://user-images.githubusercontent.com/244163/94830972-d1c2e580-0414-11eb-8584-6735fc03bfaf.png)

If I uncheck this setting, keyboard shortcuts work great. But I need to enable this setting because I'm using Turkish Keyboard and as you can see at the following image, special keys like `# $ { [ ] }` can only be typed by holding ALT key. Both left and right ALT keys work on macOS but on Ubuntu only the right ALT key works. If I don't enable that setting, I cannot use left ALT to type those special characters.

![tr-keyboard](https://user-images.githubusercontent.com/244163/94831099-fa4adf80-0414-11eb-8669-2dd5e211bd34.png)

If there is a way to enable left ALT key to type those characters, I would love to use that. Maybe there would be a way to detect Turkish (or any other) keyboards and enable left ALT key like the right one.

**Comment by rbreaves** [comment] 2020-10-01 23:19
There's always a way. Looking at this file here key.py will let you know what's available to you via xkeysnail and their proper names. You can then update kinto.py with the appropriate keymappings, I believe between my documentation and xkeysnail's documentation you can probably work out a solution for your keyboard. If you would like to fork my project and submit those changes to me I would certainly take a look at them and consider merging it or reworking it so that it can be merged.

I tend to not make international keyboard changes because I can't really dog food it myself, but I'd love to open this project up to as many keyboard layouts as possible and even update the installer to not assume a US based keymap. It might also be wise for me to start checking if any additional/abnormal keyboard options exist on a person's system before allow my installer to continue. At the very least I can remind users that unexpected behaviors may occur if they have certain options enabled and offer to either set them back to a US based default that I know works or other defaults for various languages in the future.

Since it appears you have figured out the source of your problem I will be closing this issue, but if you submit a PR to me I will take a look at it!

**Closed by rbreaves** 2020-10-01 23:19 UTC
Labels: bug
