### ISSUE TITLE
Kinto breaks after a few restarts

### ISSUE THREAD

**Issue by nIKiTaaaaaaa-coder** [rbreaves/kinto#811] opened 2023-06-04 09:10 UTC
**Describe the bug**
kinto worked for  few times and then this happened.
I installed it yesterday.

**Expected behavior**
I thought it would work.

**Install Type:** VM
**Distro:** Manjaro Linux 22.1.3
**DE:** XFCE
**Branch:** master
**Commit:** 
```
fatal: not a git repository (or any of the parent directories): .git
```

#xkeysnail
<img width="1570" alt="Снимок экрана 2023-06-04 в 12 04 28" src="https://github.com/rbreaves/kinto/assets/70052563/052ef7d1-de7c-439f-b641-1ff9821e4636">
<img width="1453" alt="Снимок экрана 2023-06-04 в 12 04 37" src="https://github.com/rbreaves/kinto/assets/70052563/3449b5e5-9b14-45ad-9c7f-e7c8909b450d">

**Screenshots**
<img width="1523" alt="Снимок экрана 2023-06-04 в 11 43 35" src="https://github.com/rbreaves/kinto/assets/70052563/95e539a1-ad20-45de-bdaa-c2a25326984a">

**Comment by nIKiTaaaaaaa-coder** [comment] 2023-06-04 09:10
This is the first time I post an issue, sorry if I did something very wrong

**Comment by RedBearAK** [comment] 2023-06-04 10:39
@nIKiTaaaaaaa-coder 

> no module named 'xkeysnail'

Maybe Manjaro updated the Python version or something similar. Try re-running the Kinto installer and see what happens.

**Comment by nIKiTaaaaaaa-coder** [comment] 2023-06-04 14:14
after reinstalling 
```
--2023-06-04 17:03:40--  https://github.com/rbreaves/kinto/archive/refs/heads/master.zip
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/rbreaves/kinto/zip/refs/heads/master [following]
--2023-06-04 17:03:40--  https://codeload.github.com/rbreaves/kinto/zip/refs/heads/master
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘/home/nikita/Downloads/kinto.zip’

/home/nikita/Downloads/kinto.zip             [  <=>                                                                            ] 678,60K  3,05MB/s    in 0,2s    

2023-06-04 17:03:40 (3,05 MB/s) - ‘/home/nikita/Downloads/kinto.zip’ saved [694889]

Archive:  /home/nikita/Downloads/kinto.zip
99a8566262ce3cf488b13fdbdb7f04d156dac8af
replace /home/nikita/Downloads/kinto-master/.gitattributes? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: /home/nikita/Downloads/kinto-master/.gitattributes  
  inflating: /home/nikita/Downloads/kinto-master/.github/ISSUE_TEMPLATE/bug_report.md  
  inflating: /home/nikita/Downloads/kinto-master/.github/ISSUE_TEMPLATE/feature_request.md  
  inflating: /home/nikita/Downloads/kinto-master/.github/ISSUE_TEMPLATE/gratitude.md  
  inflating: /home/nikita/Downloads/kinto-master/.github/ISSUE_TEMPLATE/question.md  
  inflating: /home/nikita/Downloads/kinto-master/.github/workflows/01-ubuntu-budgie.yml  
  inflating: /home/nikita/Downloads/kinto-master/.gitignore  
  inflating: /home/nikita/Downloads/kinto-master/LICENSE  
  inflating: /home/nikita/Downloads/kinto-master/README.md  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-black-invert.ico  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-black.ico  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-color-black-invert.ico  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-color-black.ico  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-color-invert-border.ico  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-color-invert.ico  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-color-white-invert.ico  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-color.ico  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-white-invert.ico  
  inflating: /home/nikita/Downloads/kinto-master/assets/kinto-white.ico  
  inflating: /home/nikita/Downloads/kinto-master/install/linux.sh  
  inflating: /home/nikita/Downloads/kinto-master/install/windows.ps1  
  inflating: /home/nikita/Downloads/kinto-master/linux/gnome_logoff.sh  
  inflating: /home/nikita/Downloads/kinto-master/linux/gui/capslock_1200x720.png  
  inflating: /home/nikita/Downloads/kinto-master/linux/gui/keys_1200x720.png  
  inflating: /home/nikita/Downloads/kinto-master/linux/gui/kinto-gui.py  
  inflating: /home/nikita/Downloads/kinto-master/linux/gui/kinto.desktop  
  inflating: /home/nikita/Downloads/kinto-master/linux/gui/tuxbg.png  
  inflating: /home/nikita/Downloads/kinto-master/linux/gui/tuxcry4.png  
  inflating: /home/nikita/Downloads/kinto-master/linux/gui/tuxerror.png  
  inflating: /home/nikita/Downloads/kinto-master/linux/gui/tuxuninstall.png  
  inflating: /home/nikita/Downloads/kinto-master/linux/initkb  
  inflating: /home/nikita/Downloads/kinto-master/linux/killdups.sh  
  inflating: /home/nikita/Downloads/kinto-master/linux/kinto-service.sh  
  inflating: /home/nikita/Downloads/kinto-master/linux/kinto.py  
  inflating: /home/nikita/Downloads/kinto-master/linux/limitedadmins  
  inflating: /home/nikita/Downloads/kinto-master/linux/prexk.sh  
  inflating: /home/nikita/Downloads/kinto-master/linux/root_logoff.sh  
  inflating: /home/nikita/Downloads/kinto-master/linux/system-config/dename.sh  
  inflating: /home/nikita/Downloads/kinto-master/linux/system-config/unipkg.sh  
  inflating: /home/nikita/Downloads/kinto-master/linux/trayapps/appindicator/icons/kinto-color-16.svg  
  inflating: /home/nikita/Downloads/kinto-master/linux/trayapps/appindicator/icons/kinto-color.svg  
  inflating: /home/nikita/Downloads/kinto-master/linux/trayapps/appindicator/icons/kinto-invert-16.svg  
  inflating: /home/nikita/Downloads/kinto-master/linux/trayapps/appindicator/icons/kinto-invert.svg  
  inflating: /home/nikita/Downloads/kinto-master/linux/trayapps/appindicator/icons/kinto-solid-16.svg  
  inflating: /home/nikita/Downloads/kinto-master/linux/trayapps/appindicator/icons/kinto-solid.svg  
  inflating: /home/nikita/Downloads/kinto-master/linux/trayapps/appindicator/icons/kinto.svg  
  inflating: /home/nikita/Downloads/kinto-master/linux/trayapps/appindicator/kintotray.desktop  
  inflating: /home/nikita/Downloads/kinto-master/linux/trayapps/appindicator/kintotray.py  
  inflating: /home/nikita/Downloads/kinto-master/linux/vscode_keybindings.json  
  inflating: /home/nikita/Downloads/kinto-master/linux/xkeysnail.desktop  
  inflating: /home/nikita/Downloads/kinto-master/linux/xkeysnail.service  
  inflating: /home/nikita/Downloads/kinto-master/linux/xkeysnail_sysv.desktop  
  inflating: /home/nikita/Downloads/kinto-master/linux/xkeystart.sh  
  inflating: /home/nikita/Downloads/kinto-master/prekinto.py  
  inflating: /home/nikita/Downloads/kinto-master/setup.py  
  inflating: /home/nikita/Downloads/kinto-master/windows/NoShell.vbs  
  inflating: /home/nikita/Downloads/kinto-master/windows/WinToMac_AltWin_swap.skl  
  inflating: /home/nikita/Downloads/kinto-master/windows/autohotkey.ps1  
  inflating: /home/nikita/Downloads/kinto-master/windows/detectUSB.ahk  
  inflating: /home/nikita/Downloads/kinto-master/windows/kinto-start.vbs  
  inflating: /home/nikita/Downloads/kinto-master/windows/kinto.ahk  
  inflating: /home/nikita/Downloads/kinto-master/windows/standard_ctrlalt_swap.skl  
  inflating: /home/nikita/Downloads/kinto-master/windows/theme_ubuntu.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/toggle_kb.bat  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/macbook_winctrl_capsesc_swap.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/macbook_winctrl_swap.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/macbook_winctrl_swap.skl  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/remove_keyswap.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/standard_ctrlalt_capsesc_swap.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/standard_ctrlalt_swap.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/theme_campbell.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/theme_legacy.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/theme_onehalfdark.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/unused/theme_onehalflight.reg  
  inflating: /home/nikita/Downloads/kinto-master/windows/usb.vbs  
  inflating: /home/nikita/Downloads/kinto-master/xkeysnail_service.sh  
Installing Kinto...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

Kinto  build 
Type in Linux like it's a Mac.


Have you run "sudo pacman -Syu" before running Kinto setup? (y/n): y
Resetting Super_L, please wait...
Success.
xfce4-popup-whiskermenu has been set to Alt-F1 for Cmd-Space to work.
Defaulting to user installation because normal site-packages is not writeable
Collecting pillow
  Downloading Pillow-9.5.0-cp311-cp311-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 11.6 MB/s eta 0:00:00
Installing collected packages: pillow
Successfully installed pillow-9.5.0
Using systemd...
localuser:root being added to access control list
fatal: destination path 'xkeysnail' already exists and is not an empty directory.
Processing /home/nikita/Downloads/kinto-master/xkeysnail
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting evdev (from xkeysnail==0.3.0)
  Using cached evdev-1.6.1.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-xlib (from xkeysnail==0.3.0)
  Using cached python_xlib-0.33-py2.py3-none-any.whl (182 kB)
Collecting inotify-simple (from xkeysnail==0.3.0)
  Using cached inotify_simple-1.3.5.tar.gz (9.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting six>=1.10.0 (from python-xlib->xkeysnail==0.3.0)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: xkeysnail, evdev, inotify-simple
  Building wheel for xkeysnail (pyproject.toml) ... done
  Created wheel for xkeysnail: filename=xkeysnail-0.3.0-py3-none-any.whl size=17520 sha256=8d090e316da32ea9f28a21f90c4d18d32edcf5b09833d16262323e9c9944796f
  Stored in directory: /tmp/pip-ephem-wheel-cache-257w2_s0/wheels/5e/bb/e7/4a30b825b9eb842629f5bb1b3f8adb1f68180886a0f4322780
  Building wheel for evdev (pyproject.toml) ... done
  Created wheel for evdev: filename=evdev-1.6.1-cp311-cp311-linux_x86_64.whl size=84245 sha256=096032efe95c30056dd62b388145a48bd1b717ec12c591b1843eace63897af55
  Stored in directory: /root/.cache/pip/wheels/b1/b1/e7/2aca5ab1b4fc67cee598ec95b9e8b60c586953a15bf4739551
  Building wheel for inotify-simple (pyproject.toml) ... done
  Created wheel for inotify-simple: filename=inotify_simple-1.3.5-py3-none-any.whl size=7688 sha256=661c1e8ed7d16c64c6eaf2fc4fd017561f874dbcdcfb2c86ad42b237215f1d3c
  Stored in directory: /root/.cache/pip/wheels/62/4d/7f/e5e1cee8d11c6cd5bde3b7a60afe4498e46123173d92dd981c
Successfully built xkeysnail evdev inotify-simple
Installing collected packages: evdev, six, inotify-simple, python-xlib, xkeysnail
Successfully installed evdev-1.6.1 inotify-simple-1.3.5 python-xlib-0.33 six-1.16.0 xkeysnail-0.3.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/home/nikita/.local/bin/xkeysnail
Service file added to /usr/lib/systemd/system/xkeysnail.service
Ownership set for root...
Permissions set to 644...
Created soft symlink...
ln: failed to create symbolic link '/etc/systemd/system/graphical.target.wants/xkeysnail.service': No such file or directory
Failed to create soft symlink for graphical target...
Failed to disable unit: Refusing to operate on alias name or linked unit file: xkeysnail.service
Adding xhost fix...

Kinto install is complete.

If the setup wizard fails to appear then please run this command.
~/.config/kinto/gui/kinto-gui.py

You can then either Google what dependencies you may be missing
or open an issue ticket.

If you are using Manjaro and see an error about 'GLIBC_2.xx not found' appears then please update your system.
sudo pacman -Syu
```
before reinstallation this worked, but now it throws an error
```
systemctl enable xkeysnail
Failed to enable unit: Refusing to operate on alias name or linked unit file: xkeysnail.service
```

**Comment by RedBearAK** [comment] 2023-06-04 19:47
@nIKiTaaaaaaa-coder 

Reminder, I am not the Kinto dev, just a long-time user of Kinto and minor contributor. 

Here is what I think is going on, but this is just a guess for now. The most recent releases of the Ubuntu flavors changed to using a "managed" Python environment (whatever that means) which caused the system to strongly discourage the use of `pip` to install Python packages outside of a Python "virtual environment". As I understand it this is basically just a script that will add the `venv` location to paths and such, and the `venv` location will have a copy of the Python interpreter and a few other things. It's annoying but not too complicated. 

But, if this is what happened on Manjaro with a rolling release update, the Kinto installer will have some difficulty working without a rewrite. You can try what I did on the Ubuntus and install `pipx` and manually install `xkeysnail` from the folder where the Kinto installer clones it, inside `kinto-main` in Downloads. And then try running the Kinto installer again. But the error you ran into doesn't look exactly the same as the one people were having on the Ubuntu distros.

Or, you can try my alternate-reality Kinto-like installer, which uses a Python virtual environment to install the necessary Python packages, so it should work if the problem is what I think it is. At least, it's been working on Manjaro for me when I tested it a few days ago, but now I'm going to do a more recent update in the Manjaro VM I'm using for testing, and see if I can still successfully install Toshy. 

You can try this at your own risk, and if you have issues with it please report them on the Toshy repo, not here. If it works, hopefully we can integrate some of what the Toshy installer does into the Kinto installer. 

https://github.com/RedBearAH/toshy

The update the Manjaro VM is doing is quite large, so it's going to take me a while to get set up to do a new Toshy installer test after the update, to verify that it will still work.

**Comment by RedBearAK** [comment] 2023-06-04 20:20
@nIKiTaaaaaaa-coder 

OK, I did the huge update in the Manjaro KDE virtual machine and then tested the Toshy installer. It's working, no issues, with Manjaro fully updated. 

You do need to reassign the `Alt+F1` keyboard shortcut so that `Cmd+Space` will open the menu, by right-clicking on the application menu icon and setting the shortcut in the preferences dialog for the menu applet, but that has nothing to do with Kinto or Toshy. The shortcut simply doesn't work the way it is set up in Manjaro KDE by default. 

This problem with the Manjaro KDE application menu shortcut, and how to fix it, is documented in the Toshy README.

**Comment by nIKiTaaaaaaa-coder** [comment] 2023-06-05 09:36
Thank you very much, I'll try it and tell my progress.

**Comment by nIKiTaaaaaaa-coder** [comment] 2023-06-05 11:35
uhm... kinto seems to start working again, but I'll try toshy too

**Comment by nIKiTaaaaaaa-coder** [comment] 2023-06-05 11:52
so.. I installed toshy and disabled kinto, and now my command key is option key (writes characters like in Mac OS), ctrl is windows (everything is ok) and option key is control (to copy I need to press option+c, NOT cmd+c). into is somehow working fine now, but toshi doesn't. I think I'm gonna continue using kinto.sh

**Closed** 2023-06-05 11:52 UTC
Labels: bug

**Comment by RedBearAK** [comment] 2023-06-05 21:02
> so.. I installed toshy and disabled kinto, and now my command key is option key (writes characters like in Mac OS), ctrl is windows (everything is ok) and option key is control (to copy I need to press option+c, NOT cmd+c). into is somehow working fine now, but toshi doesn't. I think I'm gonna continue using kinto.sh

@nIKiTaaaaaaa-coder 

Please post an issue about that in the Toshy issues. I’d like to solve that problem, by finding out the device name of your keyboard. 

https://github.com/RedBearAK/toshy/issues

**Comment by nIKiTaaaaaaa-coder** [comment] 2023-06-06 17:33
That is absolutely the same as mine: https://github.com/RedBearAK/toshy/issues/20

**Comment by RedBearAK** [comment] 2023-06-06 17:59
> That is absolutely the same as mine: [RedBearAK/toshy#20](https://github.com/RedBearAK/toshy/issues/20)

Opened an issue for you to respond to in the Toshy issues. 

https://github.com/RedBearAK/toshy/issues/21
