### ISSUE TITLE
Word-wise text-navigation not working

### ISSUE THREAD

**Issue by Saduras** [rbreaves/kinto#16] opened 2019-12-10 11:51 UTC
First of all thanks a lot for your work. I struggled for some time how to modify my keymaps and hotkeys to match the mac-style until I found your project which solved it quickly.

But unfortunately word-wise navigation (alt - left-arrow / alt - right arrow on mac) is not working for me. I saw the issue #2 where you already addressed this but it does not work for me.

I'm running Ubuntu 18.04 with x11 on a 2014 MacBook Pro. 

Can you help me figure out why it's not working? Thanks!

**Comment by rbreaves** [comment] 2020-01-21 06:38
I will take a look at this tomorrow, sorry for the delayed response.

**Comment by rbreaves** [comment] 2020-01-29 02:24
I just tested this out under sublime text and it appears to behave the same as macOS sublime text vs Ubuntu 18.04 sublime text.

The way the alt and arrow keys are handled per app under Linux I believe is simply different than how macOS typically handles it for its applications (devs following stricter standards, using specific libraries, etc.).

If someone can indicate to me otherwise, that there would be a reason to further pursue this by updating this file then please let me know, but I don't think there is much I can do to further Alt + arrow compatibility.
https://github.com/rbreaves/kinto/blob/master/.xkb/symbols/mac_gui

I have just added kintox11, a C based program, that handles a lot better than xprop and can easily be sent a basic text file of terminal app names so it can output whether the user is using a term or gui based app. kintox11 could easily be extended to all support custom keymaps (symbol files) based on another set of criteria, perhaps looking for conf files with the application name itself.

The source and files are currently up on the dev branch while I work on it.
```
git checkout 2d69c7b
```

**Comment by bravokiloecho** [comment] 2020-02-08 11:38
Hello! I'm just entering the world of linux and ubuntu from a Mac OS and this project is saving me from so much keyboard grief! But I'm also experiencing this lack of word-wise text navigation.

In VS Code on Mac OS (and all other GUI software) I'm used to `Alt + Left/Right` moving the cursor to the end of words. However, in Ubuntu with Kinto on, `Alt + left` does nothing in VS Code, and if firefox triggers the browser back.

I'm not sure exactly whether you were suggesting this was fixed, or going to be fixed, but I would love if there was a system-wide way of handling this.

Many thanks for all your work on this so far!

**Comment by cicloon** [comment] 2020-02-10 14:11
Same here, word navigation is the only thing I'm missing so far. Having this would be great.

**Comment by rbreaves** [comment] 2020-02-11 21:44
I'll re-open the issue and take another look at it since you are specifically mentioning the program you are having an issue with. I'll compare it with the macOS program of VS code, there may be a difference with specific apps, I just couldn't duplicate an issue in sublime text, but maybe we're not talking the exact some set of keys - either way I will take another look.

**Comment by bravokiloecho** [comment] 2020-02-11 22:27
That's really great, thanks so much!

And just to clarify, this `alt + left/right` behaviour of word navigation is pretty much system-wide in Mac OS (see the "Working with text" section on this page: https://www.danrodney.com/mac/#working-with-text). It's also documented here: https://support.apple.com/en-za/HT201236

So ideally this would be system wide in Linux also, apart from in the Terminal which I realise is a special case.

One more note that might help... The original key combo to do this in Ubuntu is `Ctrl + left/right` and is documented here as "Go to previous/next word" https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Text_editing

**Comment by rbreaves** [comment] 2020-02-11 23:08
As I was trying to explain earlier, making Alt + left/right a system-wide navigation feature will be exceedingly difficult, if not impossible on Linux due to the lack of consensus btwn developers on the platform.

I have installed VS Code now under linux and tested this out and appears like Alt + Left/Right is dedicated already to terminal pane focus usage, but if you remove those keymaps you can then rebind the Ctrl + Left/Right keybindings to traverse words as you are wanting. I might include some default keybindings with the install of Kinto, but currently it is outside the scope of the project, which is to focus on fixing global keymap type issues. However including some default macOS like keymaps for specific apps during and after the install is something I may be interested in doing later - it's just a lot more effort since they'd all be one off efforts.

It is apparent though that the Ctrl+Left/Right is overridden in VS Code by the Kinto remap effort to make Ctrl+Left/Right behave more like it does on macOS.

<img width="707" alt="Screen Shot 2020-02-11 at 4 58 42 PM" src="https://user-images.githubusercontent.com/10969616/74287980-e3724400-4cf0-11ea-9e41-687b92c7c1ff.png">

~/.config/Code/User/keybindings.json
```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "alt+left",
        "command": "-workbench.action.terminal.focusPreviousPane",
        "when": "terminalFocus"
    },
    {
        "key": "alt+left",
        "command": "cursorWordStartLeft",
        "when": "textInputFocus"
    },
    {
        "key": "ctrl+left",
        "command": "-cursorWordStartLeft",
        "when": "textInputFocus"
    },
    {
        "key": "alt+right",
        "command": "-workbench.action.terminal.focusNextPane",
        "when": "terminalFocus"
    },
    {
        "key": "alt+right",
        "command": "cursorWordEndRight",
        "when": "textInputFocus"
    },
    {
        "key": "ctrl+right",
        "command": "-cursorWordEndRight",
        "when": "textInputFocus"
    }
]
```

**Comment by bravokiloecho** [comment] 2020-02-12 10:05
I see, I don't think I understood that you were saying it wasn't possible earlier. And I agree that application specific keybindings is probably outside the scope of Kinto. But thank you for the help of VS Code, that certainly makes things better.

However I still find it strange that there can be no way of word-wise navigation. It works with `ctrl + right/left` without Kinto. Is there no way of mapping it to something? Even the default behaviour? It would be a real shame to lose this functionality completely as it makes typing much harder.

**Comment by owzim** [comment] 2020-02-12 12:46
@bravokiloecho @rbreaves I miss this feature as well, but I think we have to live with it not being a system wide thing and only available in apps which provide customization in this regard.

[Here's a list](https://www.howtogeek.com/115664/42-text-editing-keyboard-shortcuts-that-work-almost-everywhere/) of shortcuts on linux, which is clearly lacking of word-wise navigation.

**Comment by rbreaves** [comment] 2020-02-12 18:20
Well sorta, VS Code actually has different behavior for Ctrl + right/left under Linux & Windows vs macOS and that's really the cause for the confusion, it's more than just the placement of a key or not picking up on a global shortcut.

VS Code - Linux/Windows
Ctrl + Left/Right = move cursor to end or beginning of _word_
Alt + Left/Right = Changes Terminal pane focus

And I guess to move to the end or beginning of line you'd normally hit the Ctrl+Home or Ctrl+End key, but of course with Kinto.. your Ctrl + Left/Right is actually Ctrl+Home and Ctrl+End to move your cursor where you'd expect it to be under macOS - so there is partial implementation of the actual Word-wise functionality under VS Code just not full implementation because there's no global/system-wide shortcut to make use of how to move the cursor by word. You will have to update VS Code or a config just for VS Code would have to be added to Kinto.

I don't know if I want to be adding in one off configurations into Kinto or not, if there is a global type fix I can create or add I will, or if people want to fork my project and make proposed changes to it that includes some tweaks and specific fixes for various apps they can do so and make pull requests.

VS Code - macOS
Ctrl + Left/Right = move cursor to end or beginning of _line_
Alt + Left/Right = move cursor to end or beginning of a _word_
Cmd + Alt/Option + Left/Right = Changes Terminal pane focus

--------------------------------------

Sublime Text 3 also has small differences and changes too, such as the Find All feature.. On linux and windows it is Alt+F3 and on macOS it is Cmd+Ctrl+G. I have actually included the config keymap file for sublime text 3 a long time ago with Kinto, but I never implemented it as part of the installer, regardless I did a full comparison and corrected all the differences as it is the text editor of my choice still as I know the shortcuts well.

Anyone can do the same for VS Code if they want and submit a full key rebinding to me if they'd like as it will be the only way to get 100% consistency with the app unless you want to muck about with the xkb symbols and types files and work out what needs to happen there. You just have to be careful to not change the behavior of a modifier in a way that impacts other legit shortcuts.

If you were to fix it on the xkb side though you'd also need to update the user_config.json file to support that specific app with the new xkb keymap and restart the keyswap service. All in all.. if it were me.. you should already have like 90-95+% coverage on having similar keymaps. I'd fix it on the app unless you think it is applicable to multiple apps, thus justifying a new category and xkb keymap.

_This is just me personally, but I feel like there are only 2 categories worth creating xkb keymaps for and that is the gui and term. However Kinto supports an unlimited number of additional xkb keymaps if others want to try extending it there instead of the specific programs._ 

I just don't have the time to fulfill every possible request for hundreds of apps, my goal was and will always be to get the most coverage with the least amount of effort (although this has been an insane amount of effort to be honest to even get it to this point lol).

Also this is what the word-wise xkb keymap looks like
https://github.com/rbreaves/kinto/blob/master/.xkb/symbols/mac_gui

And this is what the sublime text 3 shortcut key configs look like.
https://github.com/rbreaves/kinto/tree/master/app-configs/sublime-text3

You also have to take into account the Chromebook keyboard layout if you want it to have complete coverage and just make some decisions on what feels best because that physical alt/ctrl position you may want to interchange a little and other times use the capslock key position as you have no choice.

**Comment by rbreaves** [comment] 2020-02-12 18:30
Deleting my overly long comment.. hmmm. Maybe there is something I can do here after all. Thanks for that link @owzim.. for some reason I was pretty certain there wasn't anything comparable but maybe.. maybe I was wrong about that. I will look into this more.

**Comment by rbreaves** [comment] 2020-02-12 21:23
I am going to re-open this issue to give it more visibility in hopes that someone might have some ideas on how to fix the symbols and types files as I am beginning to think that this might actually have a solution it just escapes me at this time.

This is one approach that I have send and commented on in the past that appears to tackle it, but in the exact opposite why that I am solving it with Kinto. Kinto checks for when your focus window changes and the reset your keyboard layout, no key interception going on at all.

This guy's approach intercepts every single keystroke and checks it against the app with the current focus and then decides whether or not to remap your key input. The approach works.. but comparatively it is a very brutefroce approach to make things work. I am not criticizing it, it should work in theory, but I also couldn't ever figure out how to get his script to actually run either.

https://github.com/joeytwiddle/dotfiles/blob/master/.config/sxhkd/sxhkdrc

https://github.com/baskerville/sxhkd/issues/123

﻿

**Comment by rbreaves** [comment] 2020-02-13 02:07
Ok guys.. @owzim, @bravokiloecho, @cicloon, and @probonobp the Alt key will now move the cursor to the left or right of the current word in the same manner as macOS. (works in VS Code and it still works in Sublime as sublime has support for both mappings by default)

I am FINALLY closing this ticket!! lol Let me know though if what's in master, 1.0.5, doesn't solve it for you guys though and I'll reopen the ticket, but I am pretty sure this update knocks it out.

https://github.com/rbreaves/kinto/commit/5d135afe5e3b792b80167b9cdcec269025c66d91

**Closed by rbreaves** 2020-02-13 02:07 UTC

**Comment by bravokiloecho** [comment] 2020-02-17 10:14
Hi @rbreaves, I'm so grateful to all your work and thinking on this issue; truly impressive. And apologies for being so slow on replying to this...

I pulled the latest version from master and ran the install process again, however nothing seems to have changed wrt the alt + arrow keys for me. I had already setup the custom keybindings in VS Code (as you described) so it was working there before. But for example, in this textarea on Github, they don't work.

Should it be working here, or were you just making a fix for VS Code? Apologies if I've misunderstood something.

**Comment by rbreaves** [comment] 2020-02-17 10:33
I’m up way too late, will have to look into it a bit later. Word-wise in browsers is not released yet, chrome is very problematic as it uses Alt arrows for back & forwards.

VS Code should already be working in master & dev unless I did something wrong in the keyswap_service.sh file that copies the files over.. I did notice my dev machine I don’t think was updating the ~/.xkb on subsequent installs. Maybe delete that directory & reinstall.

**Comment by bravokiloecho** [comment] 2020-02-17 12:03
Manually deleting the `./xkb` seemed to have done it! It looks to be working pretty good! So exciting!! Thank you!!!!!

**Comment by rbreaves** [comment] 2020-02-18 02:34
@owzim, @bravokiloecho, @cicloon, @Saduras and @probonobp Another release 1.0.5-2 has just landed if any of you guys want to check it out. This directly addresses wordwise while using web browsers and still keeping the Cmd + Arrow keys working with Back and Forwards, just like macOS, while not text field is highlighted.
