### ISSUE TITLE
Kinto not active after logout and login

### ISSUE THREAD

**Issue by owzim** [rbreaves/kinto#166] opened 2020-05-09 22:56 UTC
**Describe the bug**

`sudo systemctl status xkeysnail`:

![image](https://user-images.githubusercontent.com/1720088/81486748-46736880-9257-11ea-977e-5ffe3144fcb0.png)

**Expected behavior**

kinto should be active

**Install Type:** VM
**Distro:** Manjaro (uptodate)
**DE:** Gnome
**Branch:** master
**Commit:** 0c3e03a

**Kinto Input Caret Status**
```
cat: /tmp/kinto/caret: No such file or directory
```

**Kinto Standard Log**

`journalctl --user-unit=keyswap.service -b` has no entries, so I used `journalctl -xe`:

```
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- Automatic restarting of the unit xkeysnail.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mai 10 00:45:55 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:45:55 foo-virtualbox audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:45:55 foo-virtualbox systemd[1]: Stopped xkeysnail.
-- Subject: A stop job for unit xkeysnail.service has finished
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A stop job for unit xkeysnail.service has finished.
-- 
-- The job identifier is 6331 and the job result is done.
Mai 10 00:45:55 foo-virtualbox systemd[1]: Starting xkeysnail...
-- Subject: A start job for unit xkeysnail.service has begun execution
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has begun execution.
-- 
-- The job identifier is 6331.
Mai 10 00:45:55 foo-virtualbox kernel: audit: type=1130 audit(1589064355.000:390): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:45:55 foo-virtualbox kernel: audit: type=1131 audit(1589064355.000:391): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:45:55 foo-virtualbox bash[2626]: No protocol specified
Mai 10 00:45:55 foo-virtualbox bash[2626]: /usr/bin/xhost:  unable to open display ":0"
Mai 10 00:45:55 foo-virtualbox systemd[1]: xkeysnail.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- An ExecStartPre= process belonging to unit xkeysnail.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Mai 10 00:45:55 foo-virtualbox systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- The unit xkeysnail.service has entered the 'failed' state with result 'exit-code'.
Mai 10 00:45:55 foo-virtualbox systemd[1]: Failed to start xkeysnail.
-- Subject: A start job for unit xkeysnail.service has failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has finished with a failure.
-- 
-- The job identifier is 6331 and the job result is failed.
Mai 10 00:45:55 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mai 10 00:45:55 foo-virtualbox kernel: audit: type=1130 audit(1589064355.014:392): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mai 10 00:45:58 foo-virtualbox systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 85.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- Automatic restarting of the unit xkeysnail.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mai 10 00:45:58 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:45:58 foo-virtualbox audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:45:58 foo-virtualbox systemd[1]: Stopped xkeysnail.
-- Subject: A stop job for unit xkeysnail.service has finished
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A stop job for unit xkeysnail.service has finished.
-- 
-- The job identifier is 6384 and the job result is done.
Mai 10 00:45:58 foo-virtualbox systemd[1]: Starting xkeysnail...
-- Subject: A start job for unit xkeysnail.service has begun execution
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has begun execution.
-- 
-- The job identifier is 6384.
Mai 10 00:45:58 foo-virtualbox kernel: audit: type=1130 audit(1589064358.250:393): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:45:58 foo-virtualbox kernel: audit: type=1131 audit(1589064358.250:394): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:45:58 foo-virtualbox bash[2628]: No protocol specified
Mai 10 00:45:58 foo-virtualbox bash[2628]: /usr/bin/xhost:  unable to open display ":0"
Mai 10 00:45:58 foo-virtualbox systemd[1]: xkeysnail.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- An ExecStartPre= process belonging to unit xkeysnail.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Mai 10 00:45:58 foo-virtualbox systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- The unit xkeysnail.service has entered the 'failed' state with result 'exit-code'.
Mai 10 00:45:58 foo-virtualbox systemd[1]: Failed to start xkeysnail.
-- Subject: A start job for unit xkeysnail.service has failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has finished with a failure.
-- 
-- The job identifier is 6384 and the job result is failed.
Mai 10 00:45:58 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mai 10 00:45:58 foo-virtualbox kernel: audit: type=1130 audit(1589064358.264:395): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mai 10 00:46:01 foo-virtualbox systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 86.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- Automatic restarting of the unit xkeysnail.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mai 10 00:46:01 foo-virtualbox systemd[1]: Stopped xkeysnail.
-- Subject: A stop job for unit xkeysnail.service has finished
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A stop job for unit xkeysnail.service has finished.
-- 
-- The job identifier is 6437 and the job result is done.
Mai 10 00:46:01 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:01 foo-virtualbox audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:01 foo-virtualbox systemd[1]: Starting xkeysnail...
-- Subject: A start job for unit xkeysnail.service has begun execution
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has begun execution.
-- 
-- The job identifier is 6437.
Mai 10 00:46:01 foo-virtualbox kernel: audit: type=1130 audit(1589064361.500:396): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:01 foo-virtualbox kernel: audit: type=1131 audit(1589064361.500:397): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:01 foo-virtualbox bash[2630]: No protocol specified
Mai 10 00:46:01 foo-virtualbox bash[2630]: /usr/bin/xhost:  unable to open display ":0"
Mai 10 00:46:01 foo-virtualbox systemd[1]: xkeysnail.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- An ExecStartPre= process belonging to unit xkeysnail.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Mai 10 00:46:01 foo-virtualbox systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- The unit xkeysnail.service has entered the 'failed' state with result 'exit-code'.
Mai 10 00:46:01 foo-virtualbox systemd[1]: Failed to start xkeysnail.
-- Subject: A start job for unit xkeysnail.service has failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has finished with a failure.
-- 
-- The job identifier is 6437 and the job result is failed.
Mai 10 00:46:01 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mai 10 00:46:01 foo-virtualbox kernel: audit: type=1130 audit(1589064361.514:398): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mai 10 00:46:04 foo-virtualbox systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 87.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- Automatic restarting of the unit xkeysnail.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mai 10 00:46:04 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:04 foo-virtualbox audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:04 foo-virtualbox systemd[1]: Stopped xkeysnail.
-- Subject: A stop job for unit xkeysnail.service has finished
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A stop job for unit xkeysnail.service has finished.
-- 
-- The job identifier is 6490 and the job result is done.
Mai 10 00:46:04 foo-virtualbox systemd[1]: Starting xkeysnail...
-- Subject: A start job for unit xkeysnail.service has begun execution
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has begun execution.
-- 
-- The job identifier is 6490.
Mai 10 00:46:04 foo-virtualbox kernel: audit: type=1130 audit(1589064364.750:399): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:04 foo-virtualbox kernel: audit: type=1131 audit(1589064364.750:400): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:04 foo-virtualbox bash[2634]: No protocol specified
Mai 10 00:46:04 foo-virtualbox bash[2634]: /usr/bin/xhost:  unable to open display ":0"
Mai 10 00:46:04 foo-virtualbox systemd[1]: xkeysnail.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- An ExecStartPre= process belonging to unit xkeysnail.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Mai 10 00:46:04 foo-virtualbox systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- The unit xkeysnail.service has entered the 'failed' state with result 'exit-code'.
Mai 10 00:46:04 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mai 10 00:46:04 foo-virtualbox systemd[1]: Failed to start xkeysnail.
-- Subject: A start job for unit xkeysnail.service has failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has finished with a failure.
-- 
-- The job identifier is 6490 and the job result is failed.
Mai 10 00:46:04 foo-virtualbox kernel: audit: type=1130 audit(1589064364.764:401): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mai 10 00:46:08 foo-virtualbox systemd[1]: xkeysnail.service: Scheduled restart job, restart counter is at 88.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- Automatic restarting of the unit xkeysnail.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mai 10 00:46:08 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:08 foo-virtualbox audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:08 foo-virtualbox systemd[1]: Stopped xkeysnail.
-- Subject: A stop job for unit xkeysnail.service has finished
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A stop job for unit xkeysnail.service has finished.
-- 
-- The job identifier is 6543 and the job result is done.
Mai 10 00:46:08 foo-virtualbox systemd[1]: Starting xkeysnail...
-- Subject: A start job for unit xkeysnail.service has begun execution
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has begun execution.
-- 
-- The job identifier is 6543.
Mai 10 00:46:08 foo-virtualbox kernel: audit: type=1130 audit(1589064368.000:402): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:08 foo-virtualbox kernel: audit: type=1131 audit(1589064368.000:403): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mai 10 00:46:08 foo-virtualbox bash[2636]: No protocol specified
Mai 10 00:46:08 foo-virtualbox bash[2636]: /usr/bin/xhost:  unable to open display ":0"
Mai 10 00:46:08 foo-virtualbox systemd[1]: xkeysnail.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- An ExecStartPre= process belonging to unit xkeysnail.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Mai 10 00:46:08 foo-virtualbox systemd[1]: xkeysnail.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- The unit xkeysnail.service has entered the 'failed' state with result 'exit-code'.
Mai 10 00:46:08 foo-virtualbox systemd[1]: Failed to start xkeysnail.
-- Subject: A start job for unit xkeysnail.service has failed
-- Defined-By: systemd
-- Support: https://forum.manjaro.org/c/technical-issues-and-assistance
-- 
-- A start job for unit xkeysnail.service has finished with a failure.
-- 
-- The job identifier is 6543 and the job result is failed.
Mai 10 00:46:08 foo-virtualbox audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mai 10 00:46:08 foo-virtualbox kernel: audit: type=1130 audit(1589064368.010:404): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=xkeysnail comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
```

**Comment by rbreaves** [comment] 2020-05-10 03:29
That's surprising an old bug from before I released xkeysnail, it did show up during dev.. but I swore I had knocked that out completely.. I am not very hopeful in recreating this tbh, but I will spin it up real quick just to see what happens on the latest.

**Comment by rbreaves** [comment] 2020-05-10 03:39
Yea, I can't reproduce it on my Manjaro Gnome 19.0.2.. so when you say latest you mean that one right? Not some beta or 20 version? (Although I'd suspect it would still work) @owzim

**Comment by owzim** [comment] 2020-05-11 22:56
@rbreaves yes `manjaro-gnome-19.0.2-200312-linux54.iso` on stable channel with all updates installed

**Comment by owzim** [comment] 2020-05-11 23:04
I would like to reproduce it on a fresh manjaro but unfortunately the install fails, see https://github.com/rbreaves/kinto/issues/168

**Comment by rbreaves** [comment] 2020-05-12 00:55
Marking this as closed, appears to be resolved with #168 and that has been merged into master, dev and alpha.

The test I had preformed was the following.
1. immediate after install
working
2. log off, log on
working
3. power off, power on, log on
noticed failures of xkeysnail on boot, but worked fine when logged in
4. log off and log on again
working

In all cases it appeared to work fine.

**Closed by rbreaves** 2020-05-12 00:55 UTC
Labels: bug

**Comment by jfromaniello** [comment] 2020-10-03 17:05
I am having the same or similar issue on standard Ubuntu 20.04 with Gnome with master version pointing to commit #fa07f82184e27156a0da440e3f8774f1e299d572

1. immediate after install
 working
2. log off, log on
 working
3. power off, power on, log on
not working
unable to open display ":X"

I also noticed that the number of display will change on install / reboot

**Comment by rbreaves** [comment] 2020-10-30 04:29
Many changes have been applied for version 1.2. Please retest and let me know how it goes @jfromaniello 

https://github.com/rbreaves/kinto/commit/9ce8612f54eb32f0ec3580d2ef07b8db3ed8ce15
